- src/app/(main)/(admin)/sources/page.tsx
- src/app/api/v1/sources/route.ts
- src/core/db/importSource.ts
- src/core/db/schema.d.ts
> feat: support show the import task process

- src/app/(main)/nav.tsx
- src/app/(main)/page.tsx
Also, remove the bottom cli line, it should be put on the home page.
> chore: add a meaningful title & fix some wordings

- src/core/db/db_index.ts
- src/core/query.ts
- src/lib/kysely.ts
Simplifies the use of TiDB Serverless Vector Function for kysely developers while providing better code hints.
After PR https://github.com/tidbcloud/kysely/pull/9 merged, we will replace it with @tidbcloud/kysely
> feat: add tidb vector kysely utils

- src/app/(main)/(.)auth/login/page.client.tsx
- src/app/(main)/(admin)/settings/authentication/page.tsx
- src/app/(main)/(admin)/settings/components.tsx
- src/app/(main)/(admin)/settings/layout.tsx
- src/app/(main)/(admin)/settings/page.tsx
- src/app/(main)/nav.tsx
https://github.com/pingcap/tidb.ai/issues/14
> move authentication to settings

- src/app/(main)/layout.tsx
- src/app/(main)/nav.tsx
- src/components/site-nav-footer.tsx
https://github.com/pingcap/tidb.ai/issues/52
> update social action bar

- src/app/providers.tsx
> Set default theme to dark

- src/app/(main)/(admin)/settings/components.tsx
- src/app/(main)/(admin)/settings/layout.tsx
> Fix settings navigator

- src/app/(main)/(admin)/sources/page.tsx
- src/components/data-table.tsx
> Fix source page style

- src/app/(main)/layout.tsx
- src/components/site-nav.tsx
> Fix nav style

- src/core/db/db_index.ts
- using `cosineDistance` instead of `cosineSimilarity` as the score
- move the where condition to the external query (post filter)
> feat: using ann index

- src/app/api/test/llm-reranker/route.ts
- src/lib/llamaindex/indices/utils.ts
- src/lib/llamaindex/postprocessors/rerankers/LLMReranker.ts
- src/lib/llamaindex/prompts/defaultPrompts.ts
Add LLM reranker (inspired by Llamaindex), so that we can using LLM model to finish **rerank** work without introducing a dedicated reranker service (like cohere).
Note: By default, the range of LLM reranker's score is [0, 10]
**Query**:
```
I want to a database to replace MySQL.
```
**Rerank Result**:
```json
[
{
"node": {
"id_": "102",
"metadata": {},
"excludedEmbedMetadataKeys": [],
"excludedLlmMetadataKeys": [],
"relationships": {},
"hash": "koMWmg/c5dtM+DIi7Tfohsgz/pFSt0Zbm5NcBFznkk4=",
"text": "TiDB is a distributed, MySQL-compatible database.",
"textTemplate": "",
"metadataSeparator": "\n",
"type": "TEXT"
},
"score": 10
},
{
"node": {
"id_": "109",
"metadata": {},
"excludedEmbedMetadataKeys": [],
"excludedLlmMetadataKeys": [],
"relationships": {},
"hash": …
```
> feat: add llm reranker

- package.json
- pnpm-lock.yaml
- src/app/api/test/bitdeer-llm/route.ts
- src/lib/llamaindex/llm/bitdeer.ts
- src/lib/llamaindex/postprocessors/rerankers/LLMReranker.ts
Bitdeer is a cloud computing platform that provides computing power for cryptocurrency mining. In the AI age, Bitdeer also provides multiple managed AI models (For example, llama2, mistral, etc.) API services.
Notice: Bitderr currently only support completion-style (generate) API, doesn't support chat-style API and embedding API.
> feat: add bitdeer llm

- src/core/services/llamaindex/chating.ts
- src/core/services/llamaindex/retrieving.ts
- src/lib/collection.ts
- src/lib/llamaindex/llm/bitdeer.ts
- src/lib/llamaindex/postprocessors/rerankers/LLMReranker.ts
- src/lib/llamaindex/prompts/defaultPrompts.ts
Some LLM provider may doesn't support streaming mode for chat completion API.
> feat: chat api adapt to non-streaming mode LLM

- package.json
- pnpm-lock.yaml
- src/app/api/test/bitdeer-embedding/route.ts
- src/lib/llamaindex/embeddings/BitdeerEmbedding.ts
> fix: support config bitdeer embedding api key via env

- src/lib/llamaindex/llm/bitdeer.ts
Mock streaming mode response via non-streaming API.
> feat(bitdeer): mock stream mode chat API

- src/app/api/v1/indexes/[name]/retrieve/route.ts
- src/lib/llamaindex/postprocessors/postfilters/MetadataPostFilter.ts
> fix: add retrieve API timeout

- ddl/0-initial-schema.sql
- package.json
- pnpm-lock.yaml
- src/app/(main)/(admin)/explore/components/build-document-index-dialog.tsx
- src/app/(main)/(admin)/explore/components/columns.tsx
- src/app/(main)/(admin)/explore/components/data-table-row-actions.tsx
- src/app/(main)/(admin)/explore/page.tsx
- src/app/api/v1/documents/import/from/urls/route.ts
- src/app/api/v1/documents/index/route.ts
- src/client/operations/documents.ts
- src/components/admin-page-heading.tsx
- src/components/admin-page-layout.tsx
- src/components/data-filters/search-filter.tsx
- src/components/data-table-remote.tsx
- src/core/db/schema.d.ts
- src/core/repositories/document_import_task.ts
- src/core/repositories/document_index_task.ts
- src/core/repositories/index_.ts
- src/core/services/importing.ts
- src/core/services/indexing.ts
- src/core/services/knowledge-graph/indexing.ts
- src/core/services/llamaindex/chating.ts
- src/lib/database.ts
- src/lib/errors/api_errors.ts
- src/lib/knowledge-graph/client.ts
Add new APIs:
- `/api/v1/documents/import/from/urls`
- `/api/v1/documents/index`
> feat: add import documents from urls and build index for single/multiple documents API

- src/app/api/auth/[...nextauth]/auth.ts
- src/app/api/v1/chats/route.ts
- src/core/db/schema.d.ts
- src/core/repositories/app_access_token.ts
- src/core/services/llamaindex/retrieving.ts
- src/lib/encrypt.ts
- src/lib/errors/api_errors.ts
- src/lib/next/handler.ts
Allow using access token for authing.
> feat: support app access token

- backend/app/rag/chat.py
- backend/app/rag/chat_config.py
> Fix callback manager concurrent unsafe issue

- .gitignore
- README.md
- backend/.env.example
- backend/requirements-dev.lock
- backend/requirements.lock
- docker-compose.yml
- frontend/app/src/pages/docs/_meta.json
- frontend/app/src/pages/docs/quickstart.mdx
refer: https://github.com/pingcap/tidb.ai/issues/183
> feat: added deploy section in readme and doc

- backend/app/rag/chat.py
- backend/app/rag/chat_config.py
- backend/app/rag/knowledge_graph/base.py
- backend/app/rag/node_postprocessor/__init__.py
- backend/app/rag/node_postprocessor/metadata_post_filter.py
- backend/main.py
- backend/pyproject.toml
- backend/requirements-dev.lock
- backend/requirements.lock
New config to enable filters:
```json
{
"knowledge_graph": {
"relationship_meta_filters": {
"product": "tidbcloud"
},
},
"vector_search": {
"metadata_post_filters": {
"filters": [
{
"key": "product",
"value": "tidbcloud"
}
]
}
}
}
```
> Support simple metadata post filter

- .gitignore
- backend/app/rag/chat.py
- backend/app/rag/default_prompt.py
So the answer must not be in right language
> Fix the wrong answer language issue - missing original question in generate prompt

- .github/actions/decide/.gitignore
- .github/actions/decide/action.yml
- .github/actions/decide/index.js
- .github/actions/decide/package-lock.json
- .github/actions/decide/package.json
- .github/workflows/release.yml
- e2e/docker-compose.yml
- e2e/start-test.sh
> ci: improve PR ci performance

- backend/app/api/admin_routes/document.py
- backend/app/api/admin_routes/retrieve.py
- backend/app/repositories/document.py
- e2e/tests/api.spec.ts
Issue: https://github.com/pingcap/tidb.ai/issues/320
> feat: add more ways to filter the docs during searching

- frontend/app/src/api/documents.ts
- frontend/app/src/api/rag.ts
- frontend/app/src/components/data-table-remote.tsx
- frontend/app/src/components/documents/documents-table-filters.tsx
- frontend/app/src/components/documents/documents-table.tsx
- frontend/app/src/lib/request/params.ts
> feat(frontend): support datasource filtering

- backend/app/rag/chat_config.py
- frontend/app/src/api/chat-engines.ts
- frontend/app/src/components/chat-engine/chat-engine-options-details.tsx
- frontend/app/src/components/chat-engine/edit-option-boolean-form.tsx
- frontend/app/src/components/chat/conversation-message-groups.tsx
> feat: support hide sources

- backend/app/api/admin_routes/feedback.py
- backend/app/models/feedback.py
- frontend/app/src/api/feedbacks.ts
- frontend/app/src/components/feedbacks/feedbacks-table.tsx
> api: add chat origin to /feedbacks

- backend/app/rag/default_prompt.py
Referring to https://github.com/pingcap/tidb.ai/issues/367
> feat: add specify in refine prompt

- backend/app/rag/chat_config.py
- backend/app/rag/embed_model_option.py
- backend/app/rag/embeddings/openai_like_embedding.py
- backend/app/types.py
- frontend/app/src/pages/docs/deploy-with-docker.mdx
Support OpenAI-Like embedding models, one of them is ZhipuAI. https://github.com/pingcap/tidb.ai/issues/373
> feat: openai-like embedding model support

- backend/app/api/routes/index.py
- backend/app/api/routes/models.py
- backend/app/rag/chat.py
```json
{
"required": {
"default_llm": true,
"default_embedding_model": true,
"default_chat_engine": true,
"datasource": true,
"knowledge_base": true
},
"optional": {
"langfuse": true,
"default_reranker": true
},
"need_migration": {
"chat_engines_without_kb_configured": [
1,
60010,
90002,
240002,
240003,
360002,
390002,
420003,
420004,
450002,
480002,
570004
]
}
}
```
> feat: add need_migration field for bootstrap status

- backend/app/api/routes/chat.py
- backend/app/rag/chat.py
using kb graph editor if the chat message is completed by a chat engine with kb.
> fix: get message subgraph adapt kb

- backend/.gitignore
- backend/app/evaluation/evals.py
Added checkpoint feature for evaluation, in case cannot resume for the big batch.
> feat: added evaluation checkpoint

- frontend/app/src/api/embedding-models.ts
- frontend/app/src/app/(main)/(admin)/chat-engines/[id]/page.tsx
- frontend/app/src/app/(main)/(admin)/embedding-models/[id]/page.tsx
- frontend/app/src/app/(main)/(admin)/knowledge-bases/[id]/(tabs)/layout.tsx
- frontend/app/src/components/admin-page-heading.tsx
- frontend/app/src/components/branding.tsx
- frontend/app/src/components/chat-engine/create-chat-engine-form.tsx
- frontend/app/src/components/embedding-models/EmbeddingModelsTable.tsx
close #436 
close #429 
close #439
> fix(frontend): resolve issues

- frontend/app/src/api/commons.ts
- frontend/app/src/app/(main)/(admin)/knowledge-bases/[id]/(tabs)/layout.tsx
- frontend/app/src/components/embedding-models/EmbeddingModelsTable.tsx
- frontend/app/src/components/llm/LLMsTable.tsx
- frontend/app/src/components/reranker/RerankerModelsTable.tsx
> feat(frontend): support set default models 

- backend/app/api/admin_routes/embedding_model/models.py
- backend/app/api/admin_routes/llm/routes.py
- backend/app/api/admin_routes/reranker_model/routes.py
- backend/app/repositories/embedding_model.py
- backend/app/repositories/llm.py
- backend/app/repositories/reranker_model.py
Add new APIs:
- `PUT: /admin/llms/{llm_id}/set_default`
- `PUT: /admin/reranker-models/{reranker_model_id}/set_default`
> feat: support set default llm/embed/reranker models

- backend/app/api/admin_routes/knowledge_base/document/routes.py
- backend/app/api/admin_routes/knowledge_base/models.py
Add new API:
```
GET /api/v1/admin/knowledge_bases/{kb_id}/documents/{doc_id}
```
> feat: add get document by id API

- frontend/app/src/api/knowledge-base.ts
- frontend/app/src/components/dangerous-action-button.tsx
- frontend/app/src/components/knowledge-base/knowledge-base-card.tsx
> feat(frontend): check linked chat engines before delete kb

- backend/app/api/routes/chat.py
- backend/app/rag/chat.py
- frontend/app/src/api/chats.ts
- frontend/app/src/components/chat/message-recommend-questions.tsx
Added an API that can refresh the recommended questions
> feat: added refresh recommend question api

- frontend/app/src/app/(main)/page.tsx
- frontend/app/src/components/chat/message-input.tsx
- frontend/app/src/components/ui/dot-pattern.tsx
> ui(frontend): add a cool homepage background made by magicui.design

- backend/app/api/admin_routes/evaluation/evaluation_dataset.py
- backend/app/api/admin_routes/evaluation/evaluation_task.py
- backend/app/api/admin_routes/evaluation/models.py
- backend/app/api/admin_routes/upload.py
- backend/app/auth/users.py
- backend/app/models/evaluation_task.py
- backend/app/rag/chat.py
- backend/app/rag/utils.py
- backend/app/repositories/chat.py
- backend/app/tasks/evaluate.py
- backend/bootstrap.py
Deal with 4 issues below:
- https://github.com/pingcap/autoflow/issues/514
- https://github.com/pingcap/autoflow/issues/507
- https://github.com/pingcap/autoflow/issues/506
- https://github.com/pingcap/autoflow/issues/505
> feat: update evaluation api group

- CONTRIBUTING.md
> docs: add "How to add an API?" to CONTRIBUTING.md

- backend/app/api/admin_routes/evaluation/evaluation_dataset.py
- backend/app/api/admin_routes/evaluation/evaluation_task.py
https://github.com/pingcap/autoflow/issues/541
> feat: change the visibility of evaluation entities

- frontend/app/src/components/chat/message-content-sources.tsx
- frontend/app/src/components/chat/utils.ts
- frontend/app/src/components/documents/documents-table.tsx
> feat(frontend): support download uploaded files

- backend/app/api/admin_routes/models.py
- backend/app/api/admin_routes/retrieve.py
- backend/app/rag/retrieve.py
- backend/app/rag/retrievers/LegacyChatEngineRetriever.py
- backend/app/repositories/chunk.py
- backend/pyproject.toml
- backend/requirements-dev.lock
- backend/requirements.lock
Also:
- fix typo for `enable_kg_enhance_query_refine` parameter
> fix: upgrade pydantic to 2.10 to fix NodeWithScore serialization error

- frontend/app/src/pages/docs/embedding-model.mdx
- frontend/app/src/pages/docs/llm.mdx
https://github.com/pingcap/autoflow/issues/583
> doc: azure openai

- frontend/app/src/api/knowledge-base.ts
- frontend/app/src/components/knowledge-base/knowledge-base-chunking-config-fields.tsx
- frontend/app/src/components/knowledge-base/knowledge-base-settings-form.tsx
- frontend/app/src/components/settings-form/GeneralSettingsField.tsx
- frontend/app/src/components/settings-form/accessor-helper.ts
> feat(frontend): add chunking configuration UI for knowledge base settings

- frontend/app/src/components/chat/conversation-message-groups.tsx
> ui(frontend): allow new line in chat title

- core/autoflow/knowledge_base/base.py
- core/autoflow/knowledge_base/prompts.py
- core/autoflow/knowledge_graph/retrievers/weighted.py
- core/examples/quickstart/quickstart.ipynb
- core/pyproject.toml
- core/uv.lock
> feat: add ask method for knowledge base

- backend/app/rag/indices/knowledge_graph/graph_store/tidb_graph_store.py
- backend/uv.lock
> fix: avoid cartesian product on graph store

- frontend/app/src/components/form/utils.ts
> fix(frontend): handle form errors correctly

- backend/app/api/admin_routes/knowledge_base/graph/routes.py
- backend/app/rag/indices/knowledge_graph/graph_store/tidb_graph_store.py
- docker-compose.dev.yml
- frontend/app/package.json
- frontend/app/src/api/graph.ts
- frontend/app/src/components/chat/knowledge-graph-debug-info.tsx
- frontend/app/src/components/graph/GraphEditor.tsx
- frontend/app/src/components/graph/components/NetworkCanvas.tsx
- frontend/app/src/components/graph/components/NetworkViewer.tsx
- frontend/app/src/components/graph/network/CanvasNetworkRenderer.ts
- frontend/app/src/components/graph/network/NetworkRenderer.ts
- frontend/pnpm-lock.yaml
Update chat knowledge graph visualizer. Renderer unmouting and cleanup bugfix.
> Chat graph debugger update
