ddl/2-status-ddl.sql, src/app/api/v1/documents/preload/route.ts, src/core/db/index.ts, src/core/db/schema.d.ts, src/core/db/status.ts
TiDB Serverless uses S3 as the underlying storage for TiFlash Replica, and data may need to be loaded from S3 to the local disk during the initial query. This PR has added an API `/api/v1/documents/preload` that triggers data preloading.
The preload SQL as follows:
```sql
SELECT /*+ READ_FROM_STORAGE(TIFLASH[`document`]) */ 1 FROM `document` ORDER BY `source_uri` LIMIT 1;
```
```sql
SELECT /*+ READ_FROM_STORAGE(TIFLASH[`document_index_chunk`]) */ 1 FROM `document_index_chunk` ORDER BY `embedding` LIMIT 1;
```
=> feat: support preload tiflash replicas

extensions/html-loader/HtmlLoader.ts, extensions/html-loader/meta.ts, package.json, pnpm-lock.yaml, src/app/api/test/html-loader/route.ts, src/app/api/v1/tasks/temp_fill_document_metadata/route.ts, src/lib/zod-extensions/types/html-selector-array.ts, vercel.json
part of https://github.com/pingcap/tidb.ai/issues/121
For example:
If there is a document URL as below:
```
https://docs.pingcap.com/tidb/v6.5/character-set-and-collation
```
The reader config:
```json
{
"reader": {
"rag.loader.html": {
"metadataExtraction": [
{
"extractors": [
{
"defaultMetadata": {
"language": "en",
"version": "stable"
},
"type": "url-metadata-extractor",
"urlMetadataPattern": "/:language(zh|ja)?/:product(tidb|tidbcloud|tidb\\-data\\-migration|tidb\\-in\\-kubernetes)/:version(dev|stable|v\\d.\\d)(/.*)"
}
],
"urlPattern": "docs.pingcap.com/**"
}
]
}
}
```
The html loader will got the metadata as follows:
```json
{
"documentMetadata": {
"language": "en",
"product": "tidb",
"version": "v6.5"
}
}
```
=> feat: html loader support metadata extraction from URL

ddl/0-initial-schema.sql, extensions/html-loader/HtmlLoader.ts, src/app/api/v1/chats/route.ts, src/app/api/v1/indexes/[name]/retrieve/route.ts, src/app/api/v1/tasks/temp_fill_document_metadata/route.ts, src/components/semantic-search.tsx, src/core/db/schema.d.ts, src/core/repositories/chat_engine.ts, src/core/repositories/retrieve.ts, src/core/services/llamaindex/chating.ts, src/core/services/llamaindex/retrieving.ts, src/core/services/retrieving.ts, src/lib/llamaindex/converters/metadata-filter.ts, src/lib/llamaindex/indices/utils.ts, src/lib/llamaindex/postprocessors/postfilters/MetadataPostFilter.ts, src/lib/llamaindex/postprocessors/rerankers/LLMReranker.ts
The chatting feature now support automated metadata filter to exclude unnecessary documents.
And the `/indexes/[name]/retrive` API support pass `filters` parameters:
```json
{
"query": "Does TiDB support FK?",
"search_top_k": 200,
"filters": [
{
"name": "tidb_version",
"value": "stable"
}
],
"top_k": 10
}
```
=> feat: support metadata post filter

src/app/api/v1/chats/route.ts, src/core/services/retrieving.ts
Fix internal error if the query is empty.
> The input must not exceed the max input tokens for the model (8192 tokens for text-embedding-ada-002), cannot be an empty string.
Reference: https://platform.openai.com/docs/api-reference/embeddings/create
=> fix: zod validate query must has at least one char

ddl/0-initial-schema.sql, src/app/api/v1/documents/index/route.ts, src/core/db/schema.d.ts, src/lib/knowledge-graph/client.ts
Add `runInBackground` parameter for `/api/v1/documents/index` API
```json
{
"documentIds": [1,2,3],
"indexName": "graph",
"runInBackground": true
}
```
=> feat: support run document index tassk in background

src/app/api/test/reranker/route.ts, src/app/api/v1/indexes/[name]/retrieve/route.ts, src/core/services/llamaindex/chating.ts, src/core/services/llamaindex/indexing.ts, src/lib/llamaindex/builders/indices.ts, src/lib/llamaindex/builders/llm.ts, src/lib/llamaindex/builders/metadata-filter.ts, src/lib/llamaindex/config/metadata-filter.ts, src/lib/llamaindex/postprocessors/postfilters/MetadataPostFilter.ts
Allows config independent LLM model (such as faster and cheaper `gpt-3.5-turbo` model) for metadata-filters instead of using the llm in the `serviceContext`, which can speed up this process.
=> feat: metadata-filter support custom llm

src/app/api/v1/chat_engines/[id]/route.ts, src/app/api/v1/chats/route.ts, src/app/api/v1/indexes/[name]/retrieve/route.ts, src/core/db/schema.d.ts, src/core/repositories/chat_engine.ts, src/core/services/chating.ts, src/core/services/retrieving.ts
```bash
curl --location 'http://127.0.0.1:3000/api/v1/chats' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer xxxxxx' \
--data '{
"messages": [
{
"role": "user",
"content": "what is tidb?"
}
],
"index": "default",
"chat_engine": "jira-bot",
"stream": false
}'
```
=> feat: support stream and chat_engine options for chats api

.github/workflows/release.yml
Test this github action using [act](https://nektosact.com/introduction.html):
```bash
act workflow_dispatch --container-architecture linux/amd64 -j 'docker-metadata' --input tag=<VERSION> -s GITHUB_TOKEN=<YOUR_GITHUB_TOKEN>
```
See [version rules](https://github.com/docker/metadata-action?tab=readme-ov-file#typepep440):
- `1.2.3` => [`1`, `1.2`, `1.2.3`]
- `1.2.3beta0` => [`1.2.3b0`]
[Run with 0.1.4beta0](https://github.com/pingcap/tidb.ai/actions/runs/10381936533)
Images:
- [tidbai/backend:0.1.4b0](https://hub.docker.com/layers/tidbai/backend/0.1.4b0/images/sha256-3bcfddcecd91d95eaaae868b2bc9d453d629bc2087a8f7290a3ac703822bad42)
- [tidbai/frontend:0.1.4b0](https://hub.docker.com/layers/tidbai/frontend/0.1.4b0/images/sha256-b0ebf395ec590ce33155cc925a23bd839c969d210f8115f3d7bcc9c85baee78c?c …
=> ci: support automatic metadata for docker build

frontend/app/jest.polyfills.js, frontend/app/src/components/chat/chat-controller.ts, frontend/app/src/components/chat/conversation.test.tsx, frontend/app/src/components/chat/conversation.tsx, frontend/app/src/components/chat/message-input.tsx
=> fix(frontend): disallow empty message

.github/workflows/release.yml, e2e/prepare-test.sh, e2e/tests/chat.spec.ts, e2e/utils/chat.ts, frontend/app/src/components/chat/chat-hooks.tsx, frontend/app/src/components/chat/conversation-message-groups.tsx, frontend/app/src/components/chat/conversation.tsx, frontend/app/src/components/chat/message-answer.tsx, frontend/app/src/components/chat/message-beta-alert.tsx, frontend/app/src/components/chat/message-feedback.tsx, frontend/app/src/components/chat/message-input.tsx, frontend/app/src/components/chat/message-operations.tsx, frontend/app/src/components/ui/alert.tsx, frontend/app/src/components/ui/tooltip.tsx, frontend/app/src/components/use-size.ts, frontend/packages/widget-react/package.json, frontend/packages/widget-react/src/Widget.tsx, frontend/pnpm-lock.yaml
close #287 
close #288 
close #289 
close #291
=> style(frontend): optimize message view

backend/app/api/admin_routes/document.py, backend/app/models/document.py, backend/app/repositories/document.py, backend/pyproject.toml, backend/requirements-dev.lock, backend/requirements.lock
Since [fastapi 0.115.x](https://github.com/fastapi/fastapi/releases/tag/0.115.0), fastapi support declare`Query`,`Header`, and `Cookie` parameters with Pydantic models. Now we can wrap mutiple filters into a model in a nice way.
=> feat: upgrade fastapi to 0.115 and refine document filters

backend/Makefile, backend/app/api/admin_routes/data_source.py, backend/app/api/admin_routes/embedding_model/models.py, backend/app/api/admin_routes/embedding_model/routes.py, backend/app/api/admin_routes/knowledge_base/data_sources/models.py, backend/app/api/admin_routes/knowledge_base/data_sources/routes.py, backend/app/api/admin_routes/knowledge_base/models.py, backend/app/api/admin_routes/knowledge_base/routes.py, backend/app/api/main.py, backend/app/api/routes/chat.py, backend/app/exceptions.py, backend/app/models/knowledge_base.py, backend/app/rag/build_index.py, backend/app/rag/chat.py, backend/app/rag/chat_config.py, backend/app/rag/knowledge_base/index_store.py, backend/app/rag/knowledge_graph/graph_store/tidb_graph_editor.py, backend/app/rag/retrieve.py, backend/app/repositories/embedding_model.py, backend/app/repositories/knowledge_base.py, backend/app/repositories/llm.py, backend/app/tasks/__init__.py, backend/app/tasks/knowledge_base.py
Add KB datasource management API:
- `GET: /admin/knowledge_bases/{kb_id}/datasources`
- `POST: /admin/knowledge_bases/{kb_id}/datasources/{datasource_id}`
- `PUT:  /admin/knowledge_bases/{kb_id}/datasources/{datasource_id}`
- `DELETE: /admin/knowledge_bases/{kb_id}/datasources/{datasource_id}`
The data sources will be the exclusive resources at the knowledge base level. **The old datasource management API will be deprecated.**
=> feat: add knowledge base datasource manage API

backend/app/api/routes/chat.py, backend/app/rag/chat.py
When using stackvm as an external chat engine, the "/chat-messages/{chat_message_id}/subgraph" API endpoint still queries the deprecated `relationships` and `entities` tables. This PR fixes the issue by redirecting the queries to the corresponding `relationships_{kb_id}` and `entities_{kb_id}` tables.
=> fix: fix get message subgraph from kb

backend/app/rag/chat.py, backend/app/rag/default_prompt.py
The `structured_predict` leverages a specific tool that only exists in the OpenAI API. Drop it off.
=> fix: structured prediction is only for openai api

backend/app/api/admin_routes/upload.py, backend/app/site_settings/default_settings.yml
=> feat: add site setting upload_max_body_size

frontend/app/src/pages/docs/embedding-model.mdx, frontend/app/src/pages/docs/llm.mdx
Close #205 , #392 , and #448 .
- The LLMs and embedding models served by vLLM and Xinference have been tested to be able to work properly through the openai_like option. (#205 and #448 )
- Bge-m3 served by Ollama can also work properly. (#392 )
=> docs: add examples of vLLM and Xinference models

CONTRIBUTING.md
`docker-compose.build.yml` does not exist.
=> docs: fix dev docker compose filepath on CONTRIBUTING.md

backend/app/rag/knowledge_graph/extractor.py, backend/app/rag/knowledge_graph/graph_store/tidb_graph_store.py, backend/app/rag/knowledge_graph/intent.py, backend/app/rag/knowledge_graph/prerequisite.py
Because most of the dspy programs we are using are uncompiled versions, it is easy to have unexpected behavior, so add an explicit requirement to increase the stability of the output
=> add response format requirements

backend/app/rag/knowledge_graph/extractor.py
Error occurred when using bedrock as llm provider caused by malformed input request.
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: Malformed input request: #: subject must not be valid against schema {"required":["messages"]}#: extraneous key [response_mime_type] is not permitted, please reformat your input and try again.
=> Fix: add bedrock branch logic while creating kg index

backend/app/api/admin_routes/knowledge_base/graph/models.py, backend/app/api/admin_routes/knowledge_base/graph/routes.py, backend/app/api/admin_routes/models.py, backend/app/api/admin_routes/retrieve.py, backend/app/rag/chat_config.py, backend/app/rag/retrieve.py, backend/app/rag/vector_store/tidb_vector_store.py
close #570
For  `/admin/knowledge_bases/{kb_id}/graph/search` API, , add parameter:
- `relationship_meta_filters`: pass the filtering conditions.
For `/admin/retrieve/documents` API, add two parameters:
- `similarity_top_k` to control how many nodes should the vector search return, if not set, using the value of `top_k` by default.
- `oversampling_factor`: This is similar to the `ef_search` parameter of the HNSW index, the larger the parameter, the higher the recall rate. Since TiDB does not yet support modifying the value of `ef_search`, the current implementation uses subquery. The subquery returns the `similarity_top_k * oversampling_factor` rows, and the outer query finally returns the `similarity_top_k` rows.
- At this time, if you need to turn on `metadata_filter`, you need to …
=> feat: support relationship_meta_filters / similarity_top_k /  oversampling_factor for retrieve api

backend/app/rag/chat_config.py
When using `OpenAILikeEmbedding`, if a provider other than zhipu is configured, the bug of the authentication information error will appear when building knowledge graph.
```
[2025-01-08 03:10:38,501: INFO/ForkPoolWorker-2] HTTP Request: POST https://open.bigmodel.cn/api/paas/v4/embeddings "HTTP/1.1 401 Unauthorized"
[2025-01-08 03:10:38,507: ERROR/ForkPoolWorker-2] app.tasks.build_index.build_kg_index_for_chunk[4489bfc3-0e7c-4606-ad77-b973ef24a3f1]: Failed to build knowledge graph index for chunk #60564d4d-1522-476c-9660-ab1859ee2b1e
Traceback (most recent call last):
File "/app/app/tasks/build_index.py", line 125, in build_kg_index_for_chunk
index_service.build_kg_index_for_chunk(index_session, db_chunk)
```
This bug is due to `config.pop()`call will remove the `api_base` param from the …
=> fix: avoid OpenAILikeEmbedding always use zhipu api url when knowledge graph building

backend/supervisord.conf
Set name for celery worker so that it can be display correct in flower dashboard.
=> fix(celery): set name for celery worker

backend/app/rag/embeddings/provider.py, backend/app/rag/embeddings/resolver.py, backend/app/rag/llms/provider.py, backend/app/rag/llms/resolver.py, backend/app/utils/dspy.py, backend/pyproject.toml, backend/requirements-dev.lock, backend/requirements.lock
https://github.com/pingcap/autoflow/issues/583
=> feat: azure llm and embedding models

frontend/app/src/pages/docs/embedding-model.mdx
=> fix(docs): fix wrong parameter name in example of ollama_embeddings

backend/app/rag/chat.py
Frontend can get the trace url from db_message, so we don't need to return via another event.
=> fix: remove langfuse_url trace annotation

backend/Makefile, backend/app/api/admin_routes/knowledge_base/document/models.py, backend/app/api/admin_routes/knowledge_base/document/routes.py, backend/app/api/admin_routes/knowledge_base/routes.py, backend/app/models/document.py, backend/app/rag/chat/retrieve/retrieve_flow.py, backend/app/rag/retrievers/chunk/fusion_retriever.py, backend/app/rag/retrievers/chunk/simple_retriever.py, backend/app/repositories/__init__.py, backend/app/repositories/chunk.py, backend/app/repositories/document.py, e2e/tests/knowledge-base.spec.ts, frontend/app/src/api/datasources.ts, frontend/app/src/api/knowledge-base.ts, frontend/app/src/components/cells/actions.tsx, frontend/app/src/components/cells/link.tsx, frontend/app/src/components/dangerous-action-button.tsx, frontend/app/src/components/document-viewer.tsx, frontend/app/src/components/documents/documents-table.tsx, frontend/app/src/components/knowledge-base/knowledge-base-index.tsx
part of #580
Add new API: `/admin/knowledge_bases/{kb_id}/documents/{doc_id}/reindex`
=> feat: support single document reindex

frontend/app/src/api/chats.ts, frontend/app/src/api/graph.ts, frontend/app/src/components/chat/knowledge-graph-debug-info.tsx, frontend/app/src/components/graph/components/NetworkViewer.tsx, frontend/app/src/components/graph/components/NodeDetails.tsx, frontend/app/src/components/graph/network/NetworkRenderer.ts, frontend/app/src/components/graph/utils.ts
close #618
- if results contains only one knowledge base, use primary color as before (black in light mode, white in dark mode)
- if results contains more than one knowledge bases, use chart colors from --var-chart-{i} (maximum 5 colors supported currently.)
- nodes are clustered by given initial positions related by knowledge base index. See [source code](https://github.com/pingcap/autoflow/pull/632/files#diff-8d3ac41ab813aa1c75973f9179b00263a639951e5882b21be8cfaa52aee46213R24) for more details.
=> feat(frontend): support multiple knowledge base for network graph viewer

backend/app/models/chunk.py, backend/app/models/entity.py, backend/app/models/relationship.py, backend/app/utils/singleflight_cache.py, backend/tests/test_dynamic_models.py
The singleflight pattern ensures that for any given set of arguments,
concurrent calls to the decorated function will only result in a single
actual execution. Other threads with the same arguments will wait for
the first execution to complete and then receive the same result,
rather than triggering duplicate computations.
=> fix: replace lru_cache with singleflight_cache for dynamic model creation for multi-thread safe
